In [2]:
!pip install opencv-python


  Using cached opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl.metadata (20 kB)
Using cached opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl (39.5 MB)


In [3]:
pip install opencv-contrib-python



   ---------------------------------------- 0.0/46.2 MB ? eta -:--:--
   - -------------------------------------- 1.3/46.2 MB 6.7 MB/s eta 0:00:07
   - -------------------------------------- 1.8/46.2 MB 5.6 MB/s eta 0:00:08
   -- ------------------------------------- 2.4/46.2 MB 4.2 MB/s eta 0:00:11
   -- ------------------------------------- 2.9/46.2 MB 3.6 MB/s eta 0:00:12
   -- ------------------------------------- 3.4/46.2 MB 3.3 MB/s eta 0:00:13
   --- ------------------------------------ 3.7/46.2 MB 3.1 MB/s eta 0:00:14
   ---- ----------------------------------- 4.7/46.2 MB 3.2 MB/s eta 0:00:13
   ----- ---------------------------------- 6.0/46.2 MB 3.6 MB/s eta 0:00:12
   ------ --------------------------------- 7.3/46.2 MB 3.8 MB/s eta 0:00:11
   ------- -------------------------------- 8.7/46.2 MB 4.1 MB/s eta 0:00:10
   -------- ------------------------------- 9.4/46.2 MB 4.1 MB/s eta 0:00:09
   --------- ------------------------------ 11.0/46.2 MB 4.3 MB/s eta 0:00:09
   -

In [5]:
print(cv2.__version__)

4.11.0


In [42]:
import numpy as np
import cv2

# Load an Image

In [43]:
img = cv2.imread('./images/flamingo.jpg')

In [44]:
# Check if the image loaded successfully
if img is None:
    print("Image not loaded! Check the file path.")
else:
    print("Image loaded successfully!")

Image loaded successfully!


In [45]:
print(img)

[[[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[188 163 119]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 ...

 [[167 134  88]
  [167 134  88]
  [167 134  88]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]

 [[171 141  94]
  [171 141  94]
  [172 142  95]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]

 [[177 147 100]
  [177 147 100]
  [178 148 101]
  ...
  [177 144  98]
  [177 144  98]
  [177 144  98]]]


In [46]:
img.shape
#(rows, colums, channels-BGR format)

(640, 640, 3)

# Display an Image

In [47]:
cv2.imshow('example',img)
#cv2.waitKey(10000) #10sec in milliseconds
cv2.waitKey(0) #wait till infinity
cv2.destroyAllWindows()

# Save an Image

In [48]:
cv2.imwrite('./images/example.png',img)

True

In [49]:
saved = cv2.imwrite('./images/example.png', img)
print("Image saved successfully:", saved)


Image saved successfully: True
